ALTER TABLE "participant_owned_games" ADD CONSTRAINT "participant_owned_games_identity_uq" UNIQUE NULLS NOT DISTINCT("participant_id","game_id","platform_code");--> statement-breakpoint
ALTER TABLE "game_decision_profiles" ADD CONSTRAINT "game_decision_profiles_player_count_check" CHECK ("game_decision_profiles"."min_online_players" IS NULL OR "game_decision_profiles"."max_online_players" IS NULL OR ("game_decision_profiles"."min_online_players" > 0 AND "game_decision_profiles"."min_online_players" <= "game_decision_profiles"."max_online_players"));--> statement-breakpoint
ALTER TABLE "game_decision_profiles" ADD CONSTRAINT "game_decision_profiles_session_check" CHECK ("game_decision_profiles"."min_session_minutes" IS NULL OR "game_decision_profiles"."max_session_minutes" IS NULL OR ("game_decision_profiles"."min_session_minutes" > 0 AND "game_decision_profiles"."min_session_minutes" <= "game_decision_profiles"."max_session_minutes"));--> statement-breakpoint
ALTER TABLE "game_decision_profiles" ADD CONSTRAINT "game_decision_profiles_data_status_check" CHECK ("game_decision_profiles"."data_status" IN ('COMPLETE', 'PARTIAL', 'UNKNOWN'));--> statement-breakpoint
ALTER TABLE "game_decision_profiles" ADD CONSTRAINT "game_decision_profiles_stats_check" CHECK (("game_decision_profiles"."communication" IS NULL OR "game_decision_profiles"."communication" BETWEEN 0 AND 10) AND ("game_decision_profiles"."skill" IS NULL OR "game_decision_profiles"."skill" BETWEEN 0 AND 10) AND ("game_decision_profiles"."chaos" IS NULL OR "game_decision_profiles"."chaos" BETWEEN 0 AND 10) AND ("game_decision_profiles"."strategy" IS NULL OR "game_decision_profiles"."strategy" BETWEEN 0 AND 10) AND ("game_decision_profiles"."story" IS NULL OR "game_decision_profiles"."story" BETWEEN 0 AND 10));--> statement-breakpoint
ALTER TABLE "game_network_pools" ADD CONSTRAINT "game_network_pools_verification_check" CHECK ("game_network_pools"."verification_status" IN ('VERIFIED', 'STALE', 'UNKNOWN'));--> statement-breakpoint
ALTER TABLE "game_network_pools" ADD CONSTRAINT "game_network_pools_dates_check" CHECK ("game_network_pools"."valid_from" IS NULL OR "game_network_pools"."valid_until" IS NULL OR "game_network_pools"."valid_from" <= "game_network_pools"."valid_until");--> statement-breakpoint
ALTER TABLE "game_platform_offerings" ADD CONSTRAINT "game_platform_offerings_verification_check" CHECK ("game_platform_offerings"."verification_status" IN ('VERIFIED', 'STALE', 'UNKNOWN'));--> statement-breakpoint
ALTER TABLE "game_platform_offerings" ADD CONSTRAINT "game_platform_offerings_online_verification_check" CHECK ("game_platform_offerings"."online_requirement_verification_status" IN ('VERIFIED', 'STALE', 'UNKNOWN'));--> statement-breakpoint
ALTER TABLE "game_platform_offerings" ADD CONSTRAINT "game_platform_offerings_dates_check" CHECK ("game_platform_offerings"."valid_from" IS NULL OR "game_platform_offerings"."valid_until" IS NULL OR "game_platform_offerings"."valid_from" <= "game_platform_offerings"."valid_until");--> statement-breakpoint
ALTER TABLE "game_prices" ADD CONSTRAINT "game_prices_amount_check" CHECK ("game_prices"."amount_minor" >= 0 AND ("game_prices"."regular_amount_minor" IS NULL OR "game_prices"."regular_amount_minor" >= 0));--> statement-breakpoint
ALTER TABLE "game_prices" ADD CONSTRAINT "game_prices_quality_check" CHECK ("game_prices"."quality" IN ('VERIFIED_LOCAL', 'PROVIDER_ESTIMATE', 'LEGACY_STATIC'));--> statement-breakpoint
ALTER TABLE "game_prices" ADD CONSTRAINT "game_prices_currency_check" CHECK ("game_prices"."currency" ~ '^[A-Z]{3}$');--> statement-breakpoint
ALTER TABLE "game_subscription_availability" ADD CONSTRAINT "game_subscription_availability_access_type_check" CHECK ("game_subscription_availability"."access_type" IN ('DOWNLOAD', 'CLOUD_STREAM'));--> statement-breakpoint
ALTER TABLE "game_subscription_availability" ADD CONSTRAINT "game_subscription_availability_verification_check" CHECK ("game_subscription_availability"."verification_status" IN ('VERIFIED', 'STALE', 'UNKNOWN'));--> statement-breakpoint
ALTER TABLE "game_subscription_availability" ADD CONSTRAINT "game_subscription_availability_dates_check" CHECK ("game_subscription_availability"."valid_from" IS NULL OR "game_subscription_availability"."valid_until" IS NULL OR "game_subscription_availability"."valid_from" <= "game_subscription_availability"."valid_until");--> statement-breakpoint
ALTER TABLE "game_subscription_availability" ADD CONSTRAINT "game_subscription_availability_verified_source_check" CHECK ("game_subscription_availability"."verification_status" <> 'VERIFIED' OR ("game_subscription_availability"."source_url" IS NOT NULL AND "game_subscription_availability"."last_verified_at" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "participant_owned_games" ADD CONSTRAINT "participant_owned_games_source_check" CHECK ("participant_owned_games"."ownership_source" IN ('SELF_REPORTED', 'STEAM_FUTURE'));--> statement-breakpoint
ALTER TABLE "platform_references" ADD CONSTRAINT "platform_references_family_check" CHECK ("platform_references"."family" IN ('PC', 'XBOX', 'PLAYSTATION', 'NINTENDO', 'MOBILE', 'BROWSER'));--> statement-breakpoint
ALTER TABLE "room_candidates" ADD CONSTRAINT "room_candidates_score_check" CHECK ("room_candidates"."base_score" BETWEEN 0 AND 100);--> statement-breakpoint
ALTER TABLE "room_game_history" ADD CONSTRAINT "room_game_history_disposition_check" CHECK ("room_game_history"."disposition" IN ('PLAYED', 'DO_NOT_SHOW', 'REPLAY_OK'));--> statement-breakpoint
ALTER TABLE "room_matches" ADD CONSTRAINT "room_matches_kind_check" CHECK ("room_matches"."kind" IN ('PERFECT', 'STRONG'));--> statement-breakpoint
ALTER TABLE "room_matches" ADD CONSTRAINT "room_matches_score_check" CHECK ("room_matches"."match_score" BETWEEN 0 AND 100);--> statement-breakpoint
ALTER TABLE "room_participants" ADD CONSTRAINT "room_participants_role_check" CHECK ("room_participants"."role" IN ('HOST', 'MEMBER'));--> statement-breakpoint
ALTER TABLE "room_participants" ADD CONSTRAINT "room_participants_status_check" CHECK ("room_participants"."status" IN ('CONFIGURING', 'READY', 'LEFT'));--> statement-breakpoint
ALTER TABLE "room_participants" ADD CONSTRAINT "room_participants_pc_tier_check" CHECK ("room_participants"."pc_tier" IS NULL OR "room_participants"."pc_tier" IN ('LOW', 'MID', 'HIGH'));--> statement-breakpoint
ALTER TABLE "room_votes" ADD CONSTRAINT "room_votes_value_check" CHECK ("room_votes"."value" IN ('NO', 'MAYBE', 'YES'));--> statement-breakpoint
ALTER TABLE "rooms" ADD CONSTRAINT "rooms_status_check" CHECK ("rooms"."status" IN ('LOBBY', 'MATCHING', 'SHORTLIST', 'COMPLETED', 'CANCELLED', 'EXPIRED'));--> statement-breakpoint
ALTER TABLE "rooms" ADD CONSTRAINT "rooms_version_positive_check" CHECK ("rooms"."version" > 0);--> statement-breakpoint
ALTER TABLE "rooms" ADD CONSTRAINT "rooms_region_code_check" CHECK ("rooms"."region_code" ~ '^[A-Z]{2}$');--> statement-breakpoint
ALTER TABLE "rooms" ADD CONSTRAINT "rooms_expiry_check" CHECK ("rooms"."expires_at" > "rooms"."created_at");--> statement-breakpoint
ALTER TABLE "subscription_plan_regions" ADD CONSTRAINT "subscription_plan_regions_dates_check" CHECK ("subscription_plan_regions"."valid_from" IS NULL OR "subscription_plan_regions"."valid_until" IS NULL OR "subscription_plan_regions"."valid_from" <= "subscription_plan_regions"."valid_until");--> statement-breakpoint
ALTER TABLE "subscription_plan_regions" ADD CONSTRAINT "subscription_plan_regions_capabilities_check" CHECK (jsonb_typeof("subscription_plan_regions"."capabilities") = 'object');