ALTER TABLE "game_decision_profiles" ADD CONSTRAINT "game_decision_profiles_source_type_check" CHECK ("game_decision_profiles"."source_type" IS NULL OR "game_decision_profiles"."source_type" IN ('OFFICIAL_MANUAL', 'LICENSED_PROVIDER', 'ADMIN_IMPORT'));--> statement-breakpoint
ALTER TABLE "game_decision_profiles" ADD CONSTRAINT "game_decision_profiles_source_url_check" CHECK ("game_decision_profiles"."source_url" IS NULL OR "game_decision_profiles"."source_url" ~* '^https://');--> statement-breakpoint
ALTER TABLE "game_network_pools" ADD CONSTRAINT "game_network_pools_source_type_check" CHECK ("game_network_pools"."source_type" IN ('OFFICIAL_MANUAL', 'LICENSED_PROVIDER', 'ADMIN_IMPORT'));--> statement-breakpoint
ALTER TABLE "game_network_pools" ADD CONSTRAINT "game_network_pools_source_url_check" CHECK ("game_network_pools"."source_url" IS NULL OR "game_network_pools"."source_url" ~* '^https://');--> statement-breakpoint
ALTER TABLE "game_platform_offerings" ADD CONSTRAINT "game_platform_offerings_source_type_check" CHECK ("game_platform_offerings"."source_type" IN ('OFFICIAL_MANUAL', 'LICENSED_PROVIDER', 'ADMIN_IMPORT'));--> statement-breakpoint
ALTER TABLE "game_platform_offerings" ADD CONSTRAINT "game_platform_offerings_source_url_check" CHECK ("game_platform_offerings"."source_url" IS NULL OR "game_platform_offerings"."source_url" ~* '^https://');--> statement-breakpoint
ALTER TABLE "game_prices" ADD CONSTRAINT "game_prices_source_url_check" CHECK ("game_prices"."source_url" ~* '^https://');--> statement-breakpoint
ALTER TABLE "game_subscription_availability" ADD CONSTRAINT "game_subscription_availability_source_type_check" CHECK ("game_subscription_availability"."source_type" IN ('OFFICIAL_MANUAL', 'LICENSED_PROVIDER', 'ADMIN_IMPORT'));--> statement-breakpoint
ALTER TABLE "game_subscription_availability" ADD CONSTRAINT "game_subscription_availability_source_url_check" CHECK ("game_subscription_availability"."source_url" IS NULL OR "game_subscription_availability"."source_url" ~* '^https://');--> statement-breakpoint
ALTER TABLE "subscription_plan_regions" ADD CONSTRAINT "subscription_plan_regions_source_url_check" CHECK ("subscription_plan_regions"."source_url" IS NULL OR "subscription_plan_regions"."source_url" ~* '^https://');